database:
    name: calendar
    username: calendar
    host: postgres
    password: calendar
    backend: postgres

rabbit:
    host: rabbit
    port: 5672
    username: guest
    password: guest

prometheus:
    dequeue_metrics: "0.0.0.0:2113"
    server_metrics: "0.0.0.0:2112"
