version: "3.7"
services:
    server:
        image: antik9/calendar-server
        networks:
            - overlay
        ports:
            - "50051:50051"
        restart: on-failure
        depends_on:
            - "migrate"
            - "postgres"

    enqueue:
        image: antik9/calendar-enqueue
        networks:
            - overlay
        restart: on-failure
        depends_on:
            - "migrate"
            - "postgres"
            - "rabbit"

    migrate:
        image: antik9/calendar-migrate
        networks:
            - overlay
        restart: on-failure
        depends_on:
            - "postgres"

    dequeue:
        image: antik9/calendar-dequeue
        networks:
            - overlay
        restart: on-failure
        depends_on:
            - "rabbit"

    test:
        image: antik9/calendar-test
        networks:
            - overlay
        depends_on:
            - "server"
            - "dequeue"
            - "migrate"

    postgres_exporter:
        image: wrouesnel/postgres_exporter:v0.5.1
        environment:
            DATA_SOURCE_USER: calendar
            DATA_SOURCE_PASS: calendar
            DATA_SOURCE_URI: "postgres:5432/postgres?sslmode=disable"
            PG_EXPORTER_WEB_LISTEN_ADDRESS: ":9187"
        depends_on:
            - "postgres"
            - "prometheus"
        networks:
            - overlay
        restart: on-failure

    postgres:
        image: postgres:11.5
        environment:
            POSTGRES_PASSWORD: calendar
            POSTGRES_USER: calendar
            POSTGRES_DB: calendar
        networks:
            - overlay
        restart: on-failure
        volumes:
            - db-data:/var/lib/postgresql/data

    prometheus:
        image: prom/prometheus:v2.13.0
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        networks:
            - overlay
        restart: on-failure
        depends_on:
            - server
            - dequeue

    rabbit:
        image: rabbitmq:3.7.18
        networks:
            - overlay
        restart: on-failure

volumes:
    db-data:

networks:
    overlay:
