// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/pb/message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event_Type int32

const (
	Event_MEETING  Event_Type = 0
	Event_REMINDER Event_Type = 1
	Event_OTHER    Event_Type = 2
)

var Event_Type_name = map[int32]string{
	0: "MEETING",
	1: "REMINDER",
	2: "OTHER",
}

var Event_Type_value = map[string]int32{
	"MEETING":  0,
	"REMINDER": 1,
	"OTHER":    2,
}

func (x Event_Type) String() string {
	return proto.EnumName(Event_Type_name, int32(x))
}

func (Event_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0fbca863cd7f7995, []int{0, 0}
}

type Event struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Beginning            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=beginning,proto3" json:"beginning,omitempty"`
	End                  *timestamp.Timestamp `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	EventType            Event_Type           `protobuf:"varint,4,opt,name=eventType,proto3,enum=pb.Event_Type" json:"eventType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbca863cd7f7995, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Event) GetBeginning() *timestamp.Timestamp {
	if m != nil {
		return m.Beginning
	}
	return nil
}

func (m *Event) GetEnd() *timestamp.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *Event) GetEventType() Event_Type {
	if m != nil {
		return m.EventType
	}
	return Event_MEETING
}

func init() {
	proto.RegisterEnum("pb.Event_Type", Event_Type_name, Event_Type_value)
	proto.RegisterType((*Event)(nil), "pb.Event")
}

func init() { proto.RegisterFile("internal/pb/message.proto", fileDescriptor_0fbca863cd7f7995) }

var fileDescriptor_0fbca863cd7f7995 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8e, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xdd, 0x34, 0x55, 0x33, 0x95, 0x12, 0xe6, 0x14, 0x7b, 0x31, 0xf4, 0x94, 0x43, 0xd8,
	0x40, 0xbd, 0xf8, 0x00, 0x2e, 0xda, 0x43, 0x2b, 0x2c, 0x79, 0x81, 0x2c, 0x8e, 0x4b, 0xa0, 0x99,
	0x2c, 0xcd, 0x2a, 0xf8, 0xb4, 0xbe, 0x8a, 0xec, 0x96, 0xd2, 0x63, 0x4f, 0x33, 0xfc, 0x7c, 0xf3,
	0xcd, 0x0f, 0x8f, 0x3d, 0x7b, 0x3a, 0x72, 0x77, 0x68, 0x9c, 0x69, 0x06, 0x9a, 0xa6, 0xce, 0x92,
	0x74, 0xc7, 0xd1, 0x8f, 0x98, 0x38, 0xb3, 0x7a, 0xb2, 0xe3, 0x68, 0x0f, 0xd4, 0xc4, 0xc4, 0x7c,
	0x7f, 0x35, 0xbe, 0x1f, 0x68, 0xf2, 0xdd, 0xe0, 0x4e, 0xd0, 0xfa, 0x4f, 0xc0, 0x5c, 0xfd, 0x10,
	0x7b, 0x44, 0x48, 0xb9, 0x1b, 0xa8, 0x10, 0xa5, 0xa8, 0x32, 0x1d, 0x77, 0x7c, 0x81, 0xcc, 0x90,
	0xed, 0x99, 0x7b, 0xb6, 0x45, 0x52, 0x8a, 0x6a, 0xb1, 0x59, 0xc9, 0x93, 0x52, 0x9e, 0x95, 0xb2,
	0x3d, 0x2b, 0xf5, 0x05, 0xc6, 0x1a, 0x66, 0xc4, 0x9f, 0xc5, 0xec, 0xea, 0x4d, 0xc0, 0xb0, 0x86,
	0x8c, 0x42, 0x89, 0xf6, 0xd7, 0x51, 0x91, 0x96, 0xa2, 0x5a, 0x6e, 0x96, 0xd2, 0x19, 0x19, 0x9b,
	0xc9, 0x90, 0xea, 0x0b, 0xb0, 0xae, 0x21, 0x0d, 0x13, 0x17, 0x70, 0xb7, 0x53, 0xaa, 0xdd, 0xee,
	0xdf, 0xf2, 0x1b, 0x7c, 0x80, 0x7b, 0xad, 0x76, 0xdb, 0xfd, 0xab, 0xd2, 0xb9, 0xc0, 0x0c, 0xe6,
	0x1f, 0xed, 0xbb, 0xd2, 0x79, 0x62, 0x6e, 0xe3, 0xd3, 0xe7, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x75, 0xbb, 0x3e, 0xf9, 0x2a, 0x01, 0x00, 0x00,
}
